### ISSUE TITLE
Vue Js Syncfusion Gantt chart filter not working

### ISSUE THREAD

**Issue by jeeshma** [syncfusion/ej2-vue-ui-components#10]
> The filter not working. Please check the below code

<template>
     <div>
        <ejs-gantt ref='gantt' id="GanttContainer" :dataSource="data" :taskFields = "taskFields" :height = "height" :columns="columns" :splitterSettings = "splitterSettings" :filterSettings="filterSettings" :allowFiltering= ""></ejs-gantt>
    </div>
</template>
<script>
import Vue from "vue";
import { GanttPlugin, Filter, } from "@syncfusion/ej2-vue-gantt";
import { projectNewData } from './data-source.js';
Vue.use(GanttPlugin);
export default {
  data: function() {
      return{
            data: [
    {
        TaskID: 1,
        TaskName: 'Project initiation',
        StartDate: new Date('04/02/2019'),
        EndDate: new Date('04/21/2019'),
        subtasks: [
            {TaskID: 2, TaskName: 'Identify site location', StartDate: new Date('04/02/2019'), Duration: 0,Progress: 50, resources: [1]},
            {TaskID: 3, TaskName: 'Perform soil test', StartDate: new Date('04/02/2019'), Duration: 4, Predecessor: '2',Progress: 50, resources: [2, 3, 5]},
            {TaskID: 4, TaskName: 'Soil test approval', StartDate: new Date('04/02/2019'), Duration: 0, Predecessor: '3', Progress: 50 },
        ]
    },
    {
        TaskID: 5,
        TaskName: 'Project estimation',
        StartDate: new Date('04/02/2019'),
        EndDate: new Date('04/21/2019'),
        subtasks: [
            {TaskID: 6, TaskName: 'Develop floor plan for estimation', StartDate: new Date('04/04/2019'),Duration: 3, Predecessor: '4', Progress: 50, resources: [4]},
            {TaskID: 7, TaskName: 'List materials', StartDate: new Date('04/04/2019'),Duration: 3, Predecessor: '6', resources: [4, 8],Progress: 50},
            {TaskID: 8, TaskName: 'Estimation approval', StartDate: new Date('04/04/2019'),Duration: 0, Predecessor: '7', resources: [12, 5]}
        ]
    }],
            height: '450px',
            columns: [
            { field: 'TaskID', headerText: 'Task ID', textAlign: 'Left', width: '100' },
            { field: 'TaskName', headerText: 'Task Name', width: '250' },
            { field: 'StartDate', headerText: 'Start Date', width: '150' },
            { field: 'Duration', headerText: 'Duration', width: '150' },
            { field: 'Progress', headerText: 'Progress', width: '150' },
        ],
        taskFields: {
            id: 'TaskID',
            name: 'TaskName',
            startDate: 'StartDate',
            duration: 'Duration',
            progress: 'Progress',
            child: 'subtasks'
        },
        splitterSettings:{
            columnIndex:3
            },
        filterSettings: {
            type:'Menu'
        },
        };
  },
  provide: {
      gantt: [ Filter]
  }
};
</script>

<style>
@import '../node_modules/@syncfusion/ej2-vue-gantt/styles/material.css';
</style>

**Comment by jesusarockias** [comment]
Hi Jeeshma,

Greetings from Syncfusion support.


To enable filtering it is necessary to enable the allowFiltering property of Gantt and also inject the Filter module using Provide.Please find the code example below.

``` 
<template>
  <div>
    <ejs-gantt ref='gantt' :dataSource="data" :allowFiltering=true 
    </ejs-gantt>
  </div>
</template>
<script> 
import { GanttPlugin, Filter, } from "@syncfusion/ej2-vue-gantt";
Vue.use(GanttPlugin);
export default { 
//...
    provide: { gantt: [ Filter] }
}; 
</script>


```

Please find the below online sample link.
Link - https://ej2.syncfusion.com/vue/demos/#/material/gantt/filtering.html

Regards,
@jesusarockias

**Comment by jeeshma** [comment]
Kindly check in my code also I have put the property allowfiltering. Also added the provide

<ejs-gantt  :toolbar="toolbar" :columns= "columns"  ref='gantt' :dataSource="leavedetails" id="GanttContainer" :taskFields = "taskFields" :timelineSettings = "timelineSettings" :labelSettings="labelSettings" :gridLines= "gridLines"
                          :height = "height" :allowFiltering="true" >

--------

provide: {
      gantt: [ Toolbar, Filter ]
    },

**Comment by jeeshma** [comment]
the version of vue js is 2.6.10

**Comment by jeeshma** [comment]
I have solved the issue by using  by refrehing the gantt chart
----------

         search: function(e){
         var ganttObj = document.getElementById('GanttContainer').ej2_instances[0];
         var searchText = document.getElementById('GanttContainer_searchbar').value;
         ganttObj.search(searchText);
         **this.$refs.gantt.ej2Instances.refresh(); ////Added thi sline**
      },
