### ISSUE TITLE
Question. Are there any plans to apply timezone to the whole Calendar

### ISSUE THREAD

**Issue by Merrique** [syncfusion/ej2-vue-ui-components#101]
Hello, 
Recently I have been working a lot with yours ejs-scheduler. What I have noticed is that even if I will apply timezone prop to component all it will do is recalculate the `start_datetime` of the task however the whole Calendar is still "feeling" the local timezone of your computer. 
In most cases this does not have an impact however the situation change when the local timezone has DST change on the different day than some selected timezone (I assume that user can freely pick whichever timezone they want).

For example here is the image of task scheduled on the 26th of March 2022. Take a note that my local timezone is "Europe/Warsaw" and on the 26th there is a change from winter to summer time. In the UTC it's `startTime="2023-03-26T06:00:00Z"` and `endTime="2023-03-26T10:00:00Z"`. The selected timezone for the Calendar is "America/Denver" which does not have DST on this day (it was on the 5th March) and the task is being displayed somehow taking into consideration the fact that my local timezone has timezone change. For comparison the same task was created day later and it looks "normal"
![Screenshot from 2023-07-20 13-48-22](https://github.com/syncfusion/ej2-vue-ui-components/assets/79991096/b3cee8d2-7345-4cd0-a195-3422bee14202)

For this reason I wanted to ask if there are any plans to enforce the timezone prop to follow the Calendar, not only moving the tasks based on the timezone offset

**Comment by SwathiRavi14** [comment]
Hi @Merrique,

After reviewing your concerns, we understand that you have encountered issues with the DST (Daylight Saving Time) timezone changes when using the Scheduler. We acknowledge that the current Scheduler architecture handles these changes based solely on the system's local time zones and Scheduler component rendering handled in java script. So, it is not feasible to apply the time zone to the whole calendar.

Regards,
Swathi Ravi

**Comment by Merrique** [comment]
Thank you for the response.

Kind regards,
Joanna
