### ISSUE TITLE
ejs-grid modules not working when the grid is inside a ejs-dialog

### ISSUE THREAD

**Issue by SyncroIT** [syncfusion/ej2-vue-ui-components#104]
ejs-grid's modules such as Page and Sort are not working when the grid is inside an ejs-dialog.
No errors are being displayed. I'm pretty confident you can easily replicate this on your own. I'm using a basic ejs-grid with a local data source.

Syncfusion's version: 21.1.35

**Comment by praveenkumarkarunanithi** [comment]
Hi @SyncroIT  ,
 
Greetings from Syncfusion support. 

**Query: ejs-grid modules not working when the grid is inside a ejs-dialog**

We've attempted to replicate the problem with ejs-grid modules inside an ejs-dialog using Syncfusion version 21.1.35 but were unable to encounter the same issue. To assist you better, we've created a sample project demonstrating the correct integration:
 
Sample: [Vue sample of Grid inside dialog](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstackblitz.com%2Fedit%2Fgxzlqi-pugh9p%3Ffile%3Dsrc%252FApp.vue&data=05%7C01%7Cpraveenkumar.karunanithi%40syncfusion.com%7C529f6e0caf1c4765d46908dbc4dae951%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638320216744610236%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OQsTDDWjI4o%2FHU2QUPRuWfUpwp9xITVYlg0dqNIR8oY%3D&reserved=0)
 
This project showcases a basic ejs-grid with a local data source, similar to your scenario. Please refer to it as a reference.
 
If you're still facing issues or need further assistance, kindly provide more details or steps to replicate the problem. We're here to help ensure a smooth experience with our components. Feel free to reach out with any questions.
 
Thank you for choosing Syncfusion, and we await your response.

Thanks,
Praveenkumar Karunanithi

**Comment by SyncroIT** [comment]
It probably was a problem of mine. Thanks for helping with this useful example. 
I avoided using the dialog, but in case I'll have to use the dialog with the grid again and the problem happens again, I'll reopen an issue with more details
