### ISSUE TITLE
Inquiry on Adding New Features to ej2-vue-gantt and Integrating into Vue Project

### ISSUE THREAD

**Issue by purplewish07** [syncfusion/ej2-vue-ui-components#105]
Dear Syncfusion Support Team,

I am currently working with the ej2-vue-gantt component from the open-source repository at @syncfusion/ej2-vue-ui-components, and I'm interested in extending its functionality with additional features for a Vue.js project I am developing.

I have successfully cloned the repository and have been exploring the codebase. However, I'm looking for guidance on the best practices for adding new features to the Gantt component and compiling them in a way that is consistent with your build process. Additionally, I need assistance on properly integrating these changes into my Vue.js project using npm.

Could someone guide me?

How should I add new functionality to the ej2-vue-gantt element.
How to compile the component after modifications to ensure the output is structured correctly for npm installation.
Best practices or recommendations for integrating the modified component into my Vue.js project via npm, ensuring that it aligns with the rest of the Syncfusion UI components used in my project.
I aim to maintain compatibility with the existing Syncfusion ecosystem and would appreciate any help you can provide to accomplish this.

After cloning the repository, I have set up a local development environment with the following specifications:

Node.js: v11.15.0
npm: v6.7.0
Gulp CLI: v2.3.0
Gulp: v3.9.1
gulp-sass: v4.0.0
TypeScript: v3.3.1
Using the above environment, I have successfully executed the gulp build command within the ej2-vue-ui-components\components\gantt\ directory, leading to a successful build without any issues.

![image](https://github.com/syncfusion/ej2-vue-ui-components/assets/70552611/d47befed-36dd-49d6-94fa-3cbed19e1899)

In parallel, I have also set up a new Vue.js project to serve as the target for integrating the customized Gantt component. The Vue project environment is as follows:

Node.js: v14.15.0
Vue CLI: 5.0.8
Project initialization: 
vue create quickstart
cd quickstart
npm run serve

The Vue application is running smoothly in the development server, and I am now at the stage where I would like to integrate the locally built ej2-vue-gantt component into this Vue project.

**Comment by farveensulthana** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/FARVEE~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/FARVEE~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/FARVEE~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link="#0563C1" vlink="#954F72" style='tab-interval:.5in;
word-wrap:break-word'>


<p class=MsoNormal style='background:white'><span style='font-size:12.0pt;
color:#2D3748;background:white'>Hi Purplewish07,<o:p></o:p></span></p>

<p class=MsoNormal style='background:white'><span style='font-size:12.0pt;
color:#2D3748;background:white'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-size:12.0pt;color:#2D3748;background:white;
mso-ligatures:none'>Greetings from Syncfusion Support.<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:12.0pt;color:#2D3748;mso-ligatures:
none'><o:p>&nbsp;</o:p></span></p>

<p style='margin:0in'><span style='font-size:12.0pt;color:#2D3748;background:
white'>We have reviewed your query, and we have implemented the Vue project
with the ej2vue-gantt component. The rendering sample has been added and
updated following these steps:</span><span style='font-size:12.0pt;color:#2D3748'><o:p></o:p></span></p>

<p style='margin:0in'>&nbsp;<o:p></o:p></p>

<ul style='margin-top:0in' type=disc>
 <li class=MsoNormal style='color:#2D3748;mso-list:l3 level1 lfo1;tab-stops:
     list .5in;vertical-align:middle'><span style='font-size:12.0pt;mso-fareast-font-family:
     "Times New Roman";background:white'>Vue project created using the
     commands:</span><span style='mso-fareast-font-family:"Times New Roman"'><o:p></o:p></span></li>
</ul>

<p style='margin:0in'>&nbsp;<o:p></o:p></p>


vue create quickstart   cd quickstart   npm run serve
--




<p class=MsoNormal style='background:white'><span style='font-size:12.0pt;
color:#2D3748;background:white'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal style='background:white'><span style='font-size:12.0pt;
color:#2D3748;background:white'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal style='background:white'><span lang=NL style='font-size:
12.0pt;color:#2D3748;background:white;mso-ansi-language:NL'>UgDocument : </span><span
style='font-size:12.0pt;color:#2D3748;background:white'><a
href="https://ej2.syncfusion.com/vue/documentation/gantt/getting-started-vue"><span
lang=NL style='mso-ansi-language:NL'>https://ej2.syncfusion.com/vue/documentation/gantt/getting-started-vue</span></a></span><span
lang=NL style='font-size:12.0pt;color:#2D3748;background:white;mso-ansi-language:
NL'><o:p></o:p></span></p>

<p class=MsoNormal style='background:white'><span lang=NL style='font-size:
12.0pt;color:#2D3748;background:white;mso-ansi-language:NL'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal style='background:white'><span style='font-size:12.0pt;
color:#2D3748;background:white'>Sample link : <a
href="https://www.syncfusion.com/downloads/support/directtrac/general/ze/Vue-1138066533.zip">https://www.syncfusion.com/downloads/support/directtrac/general/ze/Vue-1138066533.zip</a></span><span
style='font-size:12.0pt;color:black;background:white'> <br>
<br>
</span><span style='font-size:12.0pt;color:black'>If you have any specific
concerns or encounter issues, please provide additional details or share a
sample that replicates the problem. We are here to assist you further.</span><span
style='font-size:12.0pt;color:#2D3748;background:white'><o:p></o:p></span></p>

<p><span style='font-size:12.0pt'>Regards,<br>
Farveen sulthana T<span style='color:#2D3748;background:white'><o:p></o:p></span></span></p>


</body>

</html>

**Comment by gsumankumar** [comment]
For housekeeping purposes, we are closing this ticket. You can create a ticket on support.syncfusion.com with the details of your code changes (preferably a PR), and we will provide you with an updated package including the details.
