### ISSUE TITLE
ej2-base causes fatal SyntaxError on IOS

### ISSUE THREAD

**Issue by franck102** [syncfusion/ej2-vue-ui-components#106]
This regular expression:
`
var LINES = new RegExp('\\n\\s+|(?<=>)\\s{1,}(?=<)', 'g');
`
is causing a fatal SyntaxError on IOS (iPhone) since javascript REs on IOS doesn't support look-behind or look-ahead.
The code lives in

`node_modules/@syncfusion/ej2-base/src/template.js`

The message is `SyntaxError: Invalid regular expression: invalid group specifier name`

**Comment by TheveshwarJayakumar** [comment]
Hi Franck102,

Thank you for bringing the reported issue to our attention.

We have validated the following scenario from our end and able to reproduce the reported issue. After further analysis, we have identified it as a bug and have promptly logged a defect report on our end. And we want to convey that it will be resolved with our Volume 4 service pack, which is expected to be rolled out at the end of January 2024.

 
You can track this bug status in the below feedback.


Feedback: [Need to resolve issue with template engine when embedding new line to the string in JavaScript | Feedback Portal (syncfusion.com)](https://www.syncfusion.com/feedback/50275/need-to-resolve-issue-with-template-engine-when-embedding-new-line-to-the-string)

 
We appreciate your understanding and patience as we work towards improving our controls. If you have any further questions or suggestions, please do not hesitate to reach out to us.

 
Regards,

Theveshwar

**Comment by Mohamed7Imran** [comment]
Hi Frank102,

We are glad to announce that our Essential Studio 2023 Volume 4 SP release v24.2.3 has been rolled out and is available for download at the following link:


https://www.syncfusion.com/forums/186513/essential-studio-2023-volume-4-service-pack-release-v24-2-3-is-available-for-download

The issue with “Vue Syncfusion on Safari 15.6.1 doesn't load ,Regex error” has been resolved in this release. To access this fix, we suggest you to update the package to the latest version v24.2.3.

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards,

Mohamed Imran T

**Comment by gsumankumar** [comment]
The reported issue has been successfully addressed in service pack release version (24.2.3). Consequently, we are closing this ticket for administrative purposes. Should you have any additional questions or concerns, please feel free to reopen the ticket, and we will be more than happy to assist you further.

**Comment by franck102** [comment]
Hi, those versions of Syncfusion still exhibit the issue:

$ npm list|grep syncfusion
├── @syncfusion/ej2-base@24.1.46
├── @syncfusion/ej2-vue-calendars@24.1.47
├── @syncfusion/ej2-vue-dropdowns@24.1.47
├── @syncfusion/ej2-vue-navigations@24.1.46
├── @syncfusion/ej2-vue-popups@24.1.46

For example in 
node_modules/@syncfusion/ej2-base/src/template.js:
`var LINES = new RegExp('\\n\\s+|(?<=>)\\s{1,}(?=<)', 'g');`

You are using look-behind regexps in several files:

![image](https://github.com/syncfusion/ej2-vue-ui-components/assets/1033413/309aa0a4-0306-4bf0-828e-99cef268c927)

This is an absolute blocker, nothing will load on an iPhone:

[Error] SyntaxError: Invalid regular expression: invalid group specifier name
	RegExp (vendor-WKFnXpEO.js:17400)
	Module Code (vendor-WKFnXpEO.js:17400)
	evaluate
	moduleEvaluation
	moduleEvaluation
	(anonymous function)
	promiseReactionJob
