### ISSUE TITLE
ejs-pivotview  not render properly since updated to 24.2.8

### ISSUE THREAD

**Issue by waiyanmintun** [syncfusion/ej2-vue-ui-components#107]
nuxt 3.10.3
ej2-vue-treegrid 24.2.8

grand total column not render properly since the last update.

if dataset has only one column, rows render, but column does not render.

**Comment by waiyanmintun** [comment]
was fixed in 24.2.9

**Comment by AngelinFaithSheeba** [comment]
Hi Waiyanmintun,
 
Sorry for the inconvenience. This is the known issue, and it has been resolved in the version v24.2.9. So, kindly update your packages to this latest version to ensure proper rendering of pivot table with single columns on your end. Additionally, we have prepared a sample for your reference.
 
Sample: https://stackblitz.com/edit/spthd1?file=src%2FApp.vue
 
**Output screenshot:** 
![image](https://github.com/syncfusion/ej2-vue-ui-components/assets/93255570/e4303f24-b8cb-4796-a930-f9a0d310e100)
 
Please let us know if you have any concerns.
 
Regards,
Angelin Faith Sheeba.
