### ISSUE TITLE
To change the duration text to Arabic

### ISSUE THREAD

**Issue by jeeshma** [syncfusion/ej2-vue-ui-components#11]
How can I  change the duration text("Days) in Gantt chart to Arabic

**Comment by jesusarockias** [comment]
Hi Jeeshma,

We can translate the Gantt default text by calling setCulture method with required culture name, with required locale text value. Please find the code example below.

```
<script>
  //...
  import { L10n, setCulture } from '@syncfusion/ej2-base';
  setCulture('ar-AE');
  L10n.load({
    'ar-AE': {
        'gantt': {
            "startDate": "تاريخ البدء",
            "endDate": "تاريخ الانتهاء",
            "duration": "المدة الزمنية",
            "progress": "تقدم",
            "days": "أيام"
        },
    }
    });
    //...
</script>                        
```

Please find the below documentation and sample link.
Document - https://ej2.syncfusion.com/vue/documentation/common/localization/#loading-translations
Sample - https://www.syncfusion.com/downloads/support/directtrac/general/ze/simplegantt301125423

You can find the default locale text for various culture for Gantt in below link.
Link – https://github.com/syncfusion/ej2-locale/blob/master/src/ar.json

Regards,
Jesus Arockia Sankaran S

**Comment by ajithr** [comment]
Hi @jeeshma ,

I hope, your requirement has been achieved with the above solution. Please get back to us if you need any further assistance on this.

Regards,
Ajith R
