### ISSUE TITLE
Pivot table selectedRowIndex is not working

### ISSUE THREAD

**Issue by NaveenReddy1** [syncfusion/ej2-vue-ui-components#111]
Firstly, thank you for providing the library. I am currently integrating the pivot view into my application and am facing an issue with row selection.

While attempting to implement row selection, I am encountering difficulties passing the index number (passed static value) using the **selectedRowIndex** key, as mentioned in the documentation. Despite cross-checking in Vue DevTools and confirming the presence of the index number, it does not seem to work as expected during rendering.

Additionally, I would like to inquire whether it is possible to pass multiple index numbers for row selection.

Your assistance in resolving these matters would be greatly appreciated. Attaching sample code for reference.

Vue version: 2
pivotview version: 23.1.41

`<ejs-pivotview
     :id="tableId"
    :data-source-settings="dataSourceSettings"
    :grid-settings="gridSettings"
    :format-settings="formatSettings"
    :cell-template="cellTemplate"
    :allow-conditional-formatting="allowConditionalFormatting"
    :selectedRowIndex="2"
    @dataBound="onDataBound"
    @load="onPivotViewLoad"
    @drillThrough="onDrillThrough"
    @cellClick="onCellClick"
  ></ejs-pivotview>`

Thank you,

**Comment by AngelinFaithSheeba** [comment]
Hi Naveen,
 
Please refer the below ticket for this github query.
 
https://support.syncfusion.com/support/tickets/575547
 
Regards,
Angelin Faith Sheeba.

**Comment by gsumankumar** [comment]
This issue has been resolved in shared [ticket](https://support.syncfusion.com/support/tickets/575547). Please feel free to reopen if you have any further queries.
