### ISSUE TITLE
Gantt chart Print

### ISSUE THREAD

**Issue by jeeshma** [syncfusion/ej2-vue-ui-components#12]
Please help need for Printing Gantt chart

**Comment by jesusarockias** [comment]
Hi Jeeshma,

Currently we don’t have printing support in Gantt chart. We have logged a feature report for this. You can track the status of this feature from below feedback link.
Link – https://www.syncfusion.com/feedback/7554/support-to-print-gantt-chart

As we already lined up some major features, we could not start this feature immediately. This feature will be implemented and included in any of our upcoming releases.

But we have already logged a feature for exporting Gantt chart in PDF file. This feature will be implemented and included in our upcoming Volume 3, 2019 main release, which is expected to be rolled out at the mid of October, 2019. You can track the status from below feedback link.
Link - https://www.syncfusion.com/feedback/6397/pdf-export-for-gantt     

Regards,
Jesus Arockia Sankaran S

**Comment by Jayakumar-Duraisamy** [comment]
@jeeshma 

We are glad to say that the support for exporting Gantt to PDF mentioned in feedback [6397 ](https://www.syncfusion.com/feedback/6397/pdf-export-for-gantt) has been provided. Please find the release notes from the below link.

Link: https://ej2.syncfusion.com/documentation/release-notes/18.1.36/?type=all#gantt

You can also refer our Online documentation and Online samples for more information on PDF Exporting in Gantt.

Online Documentation: https://ej2.syncfusion.com/documentation/gantt/pdf-export/

Online Samples: https://ej2.syncfusion.com/demos/#/material/gantt/exporting.html

Please contact us if you require any further assistance.

**Comment by Jayakumar-Duraisamy** [comment]
Hi @jeeshma 
Currently, we don't have an immediate plan of support to print the Gantt chart. Hence, we are requested to track our feedback link to get latest update. 
Link: https://www.syncfusion.com/feedback/7554/support-to-print-gantt-chart 
Hence, we are closing this thread now, Please contact us if you require any further assistance.
