### ISSUE TITLE
Gantt chart vue js auto height issue

### ISSUE THREAD

**Issue by jeeshma** [syncfusion/ej2-vue-ui-components#13]
Could you please help how I can set the height of Gantt chart in Vue js as per the row height

**Comment by jeeshma** [comment]
please help need for converting this Jquery code to Vue Js

function updateGanttHeight() { 
            var ganttObj = $("#GanttContainer").ejGantt("instance"), 
            toolbar = $("#GanttContainer_toolbarItems").height(), 
            model = ganttObj.model,             
            treeObj = ganttObj._$treegridHelper.ejTreeGrid("instance"); 
            totalLen = treeObj.getExpandedRecords(model.updatedRecords); 
            //To calculate the height of Gantt as per records count 
            var height = model.rowHeight * totalLen.length + treeObj.getHeaderContent().height() + toolbar + 20; 
            //Update height using setModel 
            var sizesettings = { height: height.toString() }; 
            ganttObj.setModel({ "sizeSettings": sizesettings }); 
        }

**Comment by jesusarockias** [comment]
> Could you please help how I can set the height of Gantt chart in Vue js as per the row height

Hi Jeeshma,

We can set the height of the Gantt component based on number of rows by setting the property height as auto. Please find the code example below.

```
<ejs-gantt ref='gantt' : dataSource="data" id="GanttContainer" :height="height">  
            //...
  </ejs-gantt>

export default {
        data: function () {
            return {
              //…
                height: 'auto',
        };

```
We have prepared a sample for your reference. Please find the below sample link.
Link – https://www.syncfusion.com/downloads/support/directtrac/general/ze/simplegantt-274710448

Regards,
Jesus Arockia Sankaran S

**Comment by jesusarockias** [comment]
> please help need for converting this Jquery code to Vue Js
> 
> function updateGanttHeight() {
> var ganttObj = $("#GanttContainer").ejGantt("instance"),
> toolbar = $("#GanttContainer_toolbarItems").height(),
> model = ganttObj.model,
> treeObj = ganttObj._$treegridHelper.ejTreeGrid("instance");
> totalLen = treeObj.getExpandedRecords(model.updatedRecords);
> //To calculate the height of Gantt as per records count
> var height = model.rowHeight * totalLen.length + treeObj.getHeaderContent().height() + toolbar + 20;
> //Update height using setModel
> var sizesettings = { height: height.toString() };
> ganttObj.setModel({ "sizeSettings": sizesettings });
> }

Please check the above solution and let us know if you still face the same problem.

**Comment by jeeshma** [comment]
I have checked with the above solution. with static data it works fine. I have to show the gantt chart data dynamically using APIs . Could you please check

**Comment by jeeshma** [comment]
The solution above is working fine. Thank you
