### ISSUE TITLE
Can I only use this software in Linux environment

### ISSUE THREAD

**Issue by guozhqi** [syncfusion/ej2-vue-ui-components#17]
Can I only use this software in Linux environment? I can use NPM but I don't know if lisence has any effect

**Comment by gurunathancs1991** [comment]
Hi @guozhqi ,
 
Thanks for contacting Syncfusion.
 
Yes, you can use this packages in Linux environment and regarding our licensing, anybody can download our NPM package. However, to use our package legally they needed to get license from us by visiting syncfusion.com and signing up for license. This is also mentioned in our licensing document in NPM package. Please find its content from GitHub link
Link: https://github.com/syncfusion/ej2-javascript-ui-controls/blob/master/controls/grids/license 
We don’t have any source level license validation, so you don’t have to do anything in your application for license validation. Our current license validation are fully based on support and new feature requests.
 
Please let us know if you have further queries 

Regards,
Gurunathan

**Comment by guozhqi** [comment]
Thank you!
