### ISSUE TITLE
Chinese

### ISSUE THREAD

**Issue by jerryyahoo** [syncfusion/ej2-vue-ui-components#19]
How to Replace Default Text with Chinese？or support i18n?

**Comment by gurunathancs1991** [comment]
Hi @jerryyahoo

Thanks for contacting Syncfusion. 

For your requirement, we recommend you to use the locale support for our component. Please find the details in below link. 
https://ej2.syncfusion.com/documentation/common/localization/

You can get the Chinese culture file from here. 
https://github.com/syncfusion/ej2-locale/blob/master/src/zh.json

Please let us know if any concerns. 

Regards,
Gurunathan
