### ISSUE TITLE
Vue TreeGrid checkbox selection does not work after datasource refresh

### ISSUE THREAD

**Issue by cdshotels-liborpansky** [syncfusion/ej2-vue-ui-components#20]
Hi,

I would like to report a Vue TreeGrid bug. You can find a working repro at [codesandbox](https://codesandbox.io/s/sf-vue-treegrid-example-tv93w).

When you select some rows and refresh dataset as described in your [documentation for grid](https://ej2.syncfusion.com/vue/documentation/grid/how-to/#how-to-refresh-the-datasource) (not a standard way how to refresh vue components, generally reactivity should take care of automatic refresh), the "select all" checkbox at the treegrid header changes behaviour and does not work anymore (component somehow remembers selected rows, when you try to select again remaining rows, checkbox changes status to selected).

Is there some workaround how to reset internal component selection?

Thank you,
Libor Pansky

**Comment by ManivannanPadmanaban** [comment]
Hi Libor, 

Greetings from Syncfusion Support. 

Query: Vue TreeGrid checkbox selection does not work after datasource refresh 

We are able to reproduce the reported issue at our end, we have consider the reported issue as bug and logged a bug report for the same. Thank you for taking the time to report this issue “TreeGrid checkbox column selection is not working properly while dataSource Refresh ” and helping us improve our product. At Syncfusion, we are committed to fixing all validated defects (subject to technological feasibility and Product Development Life Cycle ) and including the defect fix in our subsequent patch release which is expected to be roll out on or before September 11th 2019.   
  
You can track the status of the issue by using the below feedback link   
  
Feedback: https://www.syncfusion.com/feedback/8667/treegrid-checkbox-column-selection-is-not-working-properly-while-datasource-refresh  

Until then, refer the below modified sample link for work around 

Modified sample Link: https://codesandbox.io/s/sf-vue-treegrid-example-nydjp  

Regards, 
Manivannan Padmanaban.

**Comment by cdshotels-liborpansky** [comment]
Hi Manivannan, 

thank you for your time! I'm happy to hear that the issue will be targeted in future patch releases.

Unfortunately your workaround solves the issue only partially - the button is reset correctly after refresh, first click selects all treegrid rows, but hitting the button one more time resets the grid and button is not working anymore.

**Comment by cdshotels-liborpansky** [comment]
The problem is not present anymore after updating to the latest version. Thank you!
