### ISSUE TITLE
Overview doesn't work if the diagram nodes shape is native 

### ISSUE THREAD

**Issue by nautilebleu** [syncfusion/ej2-vue-ui-components#21]
I have a diagram for which we want to add an overview.

It crashes in two different places if if the diagram nodes shape is native while working if the shape is set as Flow.

The first place is if I try to pan 

```
overview.js?7c77:530 Uncaught TypeError: Cannot read property 'getBBox' of null
    at Overview.translateOverviewRectangle (overview.js?7c77:530)
    at Overview.mouseMove (overview.js?7c77:703)
```

The second place is if I try to draw a new zone on the overview

```
overview.js?7c77:854 Uncaught TypeError: Cannot read property 'appendChild' of null
    at Overview.initHelper (overview.js?7c77:854)
    at Overview.mouseMove (overview.js?7c77:686)
```

In this case, the code crashes because this line

`var g = this.element.getElementsByTagName('svg')[2];`

matches a SVG node of the diagram within the overview and not one of the overview.

**Comment by gshyam93** [comment]
Hi Nautilebleu,

We have created an overview sample and tested your requirement. We are unable to replicate an issue at our end. Could  you please share us more details such as modify the below sample and video to demonstrate an issue.

Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/OverviewSample1805952028

Regards,
Shyam G

**Comment by nautilebleu** [comment]
Hi and thanks for your quick answer.

Here's two video of the problem

First with the node's shape defined as following

 ```
 obj.shape = {
          type: 'Native',
          cornerRadius: 2,
          content: `<g xmlns="http://www.w3.org/2000/svg">
            <rect x="0" width="${this.rectSize('width')}"
                  height="${this.rectSize('height')}"
                  rx="${this.rectSize('rx')}"
                  fill="${this.colorFromAction(obj.data)}" />
              <svg x="8" y="20" style="color: #fff;">
                ${this.iconFromAction(obj.data)}
              </svg>
            </g>`
        }
```

[cms-zm-2019-09-10-overview-custom.mov.zip](https://github.com/syncfusion/ej2-vue-ui-components/files/3595804/cms-zm-2019-09-10-overview-custom.mov.zip)

Note the 2 errors in the devtools console, depending of the movement I try to make.

Then if I replace the previous code by the following

```
      obj.shape = {
          type: 'Flow'
        }
```

The overview works as excepted (note that the hot reload has occured between the two videos)

[cms-zm-2019-09-10-overview-flow.mov.zip](https://github.com/syncfusion/ej2-vue-ui-components/files/3595808/cms-zm-2019-09-10-overview-flow.mov.zip)

I take a look at your sample 

Regards

**Comment by nautilebleu** [comment]
OK I think I've found the problem : my SVG contains an <svg> tag. I look to remove it but I use it to include an icon provided by vue-feather icon, not sure how the icon will respond.

**Comment by nautilebleu** [comment]
It was the problem, thanks for helping me see the problem
