### ISSUE TITLE
Organization chart

### ISSUE THREAD

**Issue by jeeshma** [syncfusion/ej2-vue-ui-components#22]
Hi,
Colud you please help me to set the width of the connector lines in Orgnaization chart .I want to reduce

**Comment by gshyam93** [comment]
Hi Jeeshma, 

Please use connector style strokeWidth property to change the width of the connector. Please refer to an code example below in which we have set a connector strokeWidth in getConnectorDefaults function.  In this function, we can set a default connector values to apply to all connectors in the diagram.

**Code example:**
 <ejs-diagram ref='diagramObj' style='display:block' id="diagram" :  :getConnectorDefaults='getConnectorDefaults'  
  ></ejs-diagram> 

//Sets the default values of a connector 
      getConnectorDefaults: (obj) => { 
          
           //change the width of connector 
           obj.style.strokeWidth = 5; 
  
      }, 


**Help documentation:** https://ej2.syncfusion.com/vue/documentation/api/diagram/strokeStyle/#strokewidth 

Regards, 
Shyam G

**Comment by jeeshma** [comment]
Thank You. I need to make the connector line area width. Please find the attached image 
![Screenshot_2019-09-10 Task+](https://user-images.githubusercontent.com/6050334/64604186-61d95b80-d3ca-11e9-8d37-bc4295a68f6d.png)

**Comment by Sridhar-Narasimhan** [comment]
Provided solution and no update for a long time. Closing this item
