### ISSUE TITLE
Diagram scrolling using MacBook Pro trackpad

### ISSUE THREAD

**Issue by nautilebleu** [syncfusion/ej2-vue-ui-components#24]
Hi,

Scrolling in diagram using the MacBook trackpad is buggy, especially horizontally.

See the video around timecode 00:00:03-00:00:06 : I try to go the the left but can't reach the most left side. 

There's no problem usign the scrollbars with the mouse cursor

[cms-zm-2019-09-10-scroll.mov.zip](https://github.com/syncfusion/ej2-vue-ui-components/files/3596178/cms-zm-2019-09-10-scroll.mov.zip)

**Comment by gshyam93** [comment]
Hi Goulwen,

We have checked a scrolling with mouse in our mac machine and it is working fine at our end. Please refer to a video below. Could you please share us more details such as browser and its version in mac machine and how you are doing horizontal scroll(other than shift + scroll) with mouse.

Video: https://www.syncfusion.com/downloads/support/directtrac/general/ze/overviewissue-1328147185

Regards,
Shyam G

**Comment by nautilebleu** [comment]
Hi Shyam,

I can give you more insights:

1. I use a MacBook Pro with a Touch Bar with a Retina Display (end 2016) I mostly use Chrome for developing (see 4. about Firefox)
2. We don't use shift+scroll but 2 fingers on the trackpad. In the video I listen the scroll of a mouse so it's not exactly what we do.
3. My MacBook Pro Touch Bar with a Retina Display is currently on repair so I use a MacBook Air without Retina display and things are really better with this configuration. Also our marketing lead tests on a Mac Book Pro Touch Bar (same as mine) with an external display: she encounters the problem when she uses the internal Retina display but not the external screen (which is a classical 24" HD display) So it seems to be tied mostly to the Retina Display (and for part worsen by the Track Pad)
4. It's not directly linked but as we speak about the Retina display: On the MacBook Pro Touch Bar with a Retina Display, the SVG boxes in the diagram are smaller than it should be. They are ok with Chrome/Safari. But they are all good with Firefox on the MacBook Air. So it seems that there's a small issue with Firefox  on Mac with Retina Display. I will file a separated bug issue on this when I'll get back my Mac Book Pro 

Also you can access to our development website here
http://devcms.greenbureau.com/skills/2189/bots/cfoWtSageW4LKuo6bhP7EJ/channel/web/trees
(there's no authentication, for now )

Regards,

Goulwen

**Comment by gshyam93** [comment]
Hi Goulwen,

We are unable to open your link. It shows the authentication issue. Could you please share your link without authentication, so that we will check at our end.

Regards,
Shyam G

**Comment by nautilebleu** [comment]
Hi

As I said in my latest message, we were working on adding the authentication (in fact we add it yesterday^^)

So here's a link with an authentication token that will last for a very long time

http://devcms.greenbureau.com/skills/2189/bots/#token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ2bWhfc2l0ZSIsImlhdCI6MTU2OTUwMDY4Niwic2tpbGwiOjIxODksImV4cCI6MTkyOTUwMDY4Nn0.htX1PXEw3V0xKrRjp5NYlyGa3nWuEXA8-fboMzjajh92ampsHGFhMSrr_BhPygo-58Z3xn-EUcxOiZYAzyaQnw

Regards, 

Goulwen

**Comment by gshyam93** [comment]
Hi Goulwen,

we can have a meeting to discuss about your issue. so please mail to support@syncfusion.com for more details.

Regards,
Shyam G

**Comment by Sridhar-Narasimhan** [comment]
We have asked for a meeting. But still, we have not yet got any comments from October 4, 2020. So we will close this issue as a   long-overdue.
