### ISSUE TITLE
Unknown Component in Production

### ISSUE THREAD

**Issue by tfpdeveloper** [syncfusion/ej2-vue-ui-components#28]
When I run in dev environment ( i.e npm run dev), components are mounted perfectly. But if I run production script (i.e npm run production), components are shown blank and in Vue devtools, it shows <E> (I guess that means unknown component.

I am using Laravel + vue (with webpack). Nothing different. Basic config. Other vue components work perfectly. Only Syncfusion components have issues

I am importing components in app.js

**Comment by BanupriyaSelvaraj** [comment]
Hi @tfpdeveloper ,

Based on your query, We have prepared a sample but we are unable to reproduce the issue  at our end. Please find the below sample link for more information.  

Sample:  https://www.syncfusion.com/downloads/support/directtrac/258331/ze/laravel-vue-17508810591912240207 

If you still had the issue,  Please share the below details that will be helpful for us to provide better solution   

1.Please try to reproduce the issue with our above attached sample.
2.Please share your issue scenario in video demonstration.

Regards,
Banupriya

**Comment by ajithr** [comment]
Hi @tfpdeveloper,

We are marking this thread as closed. Please reopen if you need any further assistance with this.

Regards,
Ajith R
