### ISSUE TITLE
Nodes' annotations is doubled when diagram loaded from serialized JSON

### ISSUE THREAD

**Issue by erhansaydam** [syncfusion/ej2-vue-ui-components#32]
I am saving the diagram to a json string as explained in https://ej2.syncfusion.com/vue/documentation/diagram/serialization. However when I load data, Although all the nodes expose at their places correctly, the annotaion text is doubled up.

When I inspect the diagram nodes (by console log diagramIstance) I observe there is ony one item in the node.annotations property and its content contains ony one text. There is no reason for it to be twice.

I have attached a sample of this situation. As you may see in the last image, there is only one item in the annotations Array.

Thank you for your help.

Best regards.

![image](https://user-images.githubusercontent.com/27196863/72736783-65b68f00-3baf-11ea-9b10-460020f75fde.png)
-------------------------
![image](https://user-images.githubusercontent.com/27196863/72736841-81219a00-3baf-11ea-9ebb-7001a5550572.png)
--------------------------
![image](https://user-images.githubusercontent.com/27196863/72736964-b29a6580-3baf-11ea-970a-083dd8a45482.png)

**Comment by erhansaydam** [comment]
I have just realized that when I use newline escape sequence (\n) in content, this problem occurs. Otherwise there is no problem. Is there another way to divide line in annotation content? The <br> tag does not resolve it.

Thank you,
Bestt regards...

**Comment by gshyam93** [comment]
Hi Erhan Saydam,

We have created a Vue sample in which we have set \n for the node annotations and performed save and load operations. We could not able to replicate an issue at our end. Could you please check in the below sample? Still if you face issues, please share us more details such as modify the below sample and OS, browser details of your machine.

Code example:
let nodes = [
  {
    id: "NewIdea",
    height: 60,
    offsetX: 300,
    offsetY: 80,
    shape: { type: "Flow", shape: "Terminator" },
    annotations: [
      {
        content: "Are you\n ready to Place Order"
      }
    ]
  },
 
   
];



Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/VueAnnotationSample-364125570

Regards,
Shyam G

**Comment by erhansaydam** [comment]
Hi Shyam,

Thank you very much for your concern. Your project is running precisely. 

I had been adding and updating annotations at runtime and I have done many changes on the original problematic code and have removed \n to discard issue. 

Now I get back \n in the annotation and surprisingly it runs precisely. I think, may be there were some environmental, parametric differences or caching problems I can not diagnose why did it happen.

Now there is no problem any more.

Thank you for your interest.

Best regards.
Erhan Saydam
