### ISSUE TITLE
Exporting native svg issue in Diagram

### ISSUE THREAD

**Issue by erhansaydam** [syncfusion/ej2-vue-ui-components#34]
Hello Syncfusion Team,

I am using Vue Diagram and want to export or print diagram where there are native svg nodes. When I export it in either formats (svg,png etc) it does not export nodes, other basic components (such as connectors exports truely) like in the screenshots below

![image](https://user-images.githubusercontent.com/27196863/73070323-18913080-3ec1-11ea-804a-e696f6a8cc74.png)

![image](https://user-images.githubusercontent.com/27196863/73070402-4aa29280-3ec1-11ea-9840-a0a0bf67be27.png)

I think exportImage method may resolve it but I can not use it like the code below because it throws error.

PrintDiagram() {

        let options = {};

        options.mode = 'Data';

        options.format = 'PNG';

        console.log(diagramInstance.exportImage(options));

      }

Can you help me how to export image of diagram with native svg nodes?

Thank you,

Best Regards
Erhan Saydam

**Comment by gshyam93** [comment]
Hi Erhan Saydam, 

We can export native or HTML node to image format using webkit rendering engine. We have created an Vue sample in which we have created a SVG nodes and established a connection with connectors. Also, we have placed convertToImage button in Vue sample. When you click on button, we send an base64 data from client side to server side. 
In the server side, we convert base64data to image using webkit converter and sent base64data to client side and downloaded an image in client side. Please refer to an sample below. 

Vue Client side sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/VueSample472475141

Server side sample:  https://www.syncfusion.com/downloads/support/directtrac/general/7z/webkitsample-1385031527 

Please refer to a help documentation to know more about webkit. 

Help documentation: https://help.syncfusion.com/file-formats/pdf/convert-html-to-pdf/webkit 

https://help.syncfusion.com/file-formats/pdf/converting-html-to-pdf?_ga=2.172509411.1701894485.1565605963-1865977539.1565150297 


Kb document: https://www.syncfusion.com/kb/8160/export-html-native-node-into-image-format

Regards, 
Shyam G

**Comment by erhansaydam** [comment]
Hi Shyam G,

Thank you for your explanatory reply. 

Actually we are using Python in backend but we have had a look at for the python solutions for the webkit engine and found some good libraries.

I understand that there is no way to solve it in client-side only. Our aim was while saving the diagram and posting its json string to backend, we may also generate a base64 thumbnail of diagram and send it to server-side as well. But no matter, we will do it on your way.

Much appreciated.

Best regards,
Erhan Saydam.
