### ISSUE TITLE
Initialize the Toolbar using HTML elements with Popup mode - how to close popup?

### ISSUE THREAD

**Issue by 7iomka** [syncfusion/ej2-vue-ui-components#35]
Hi!
Thanks for awesome components.
I use Toolbar with my own HTML elements with Popup mode.
![image](https://user-images.githubusercontent.com/18473137/73660522-040f1e00-46a1-11ea-9842-2338ef238201.png)
All works fine, except the fact that I don't know how to manually close popup?
In my case I need to handle on click on each action-button in my toolbar, and in if is button inside popup, after click I want to close popup.
In docs i'm not found any method to close popup if is open.
Thanks!

**Comment by VengateshManiraj** [comment]
Dear Customer, 

Greetings from Syncfusion Support. 

We have validated your reported scenario by preparing the sample. When we select any of the items in the toolbar popup or by clicking outside of the popup, it will be closed automatically. Since it is the default behavior of the Toolbar component. 

Sample: https://stackblitz.com/edit/teuykt?file=index.js 

Kindly refer to the above sample and let us know for further assistance.  

Regards,  
Vengatesh

**Comment by 7iomka** [comment]
> Dear Customer,
> 
> Greetings from Syncfusion Support.
> 
> We have validated your reported scenario by preparing the sample. When we select any of the items in the toolbar popup or by clicking outside of the popup, it will be closed automatically. Since it is the default behavior of the Toolbar component.
> 
> Sample: https://stackblitz.com/edit/teuykt?file=index.js
> 
> Kindly refer to the above sample and let us know for further assistance.
> 
> Regards,
> Vengatesh

Hi. Your demo is not consistent: I mentioned that I use Toolbar with my own HTML elements ( I not used variant with items config, and I also not used item component)
I just used example from your docs with user defined custom layout (divs structure).

**Comment by VengateshManiraj** [comment]
Dear Customer, 
 
Thanks for the update. 
 
We have validated your scenario at our end and we do not provide any support to close the popup manually. So we suggest you use the below code in your application to close the popup manually. 

`**document.body.click()** ` 

Please let us know for further assistance.   
 
Regards, 
Vengatesh

**Comment by rajendranr-5483** [comment]
@7iomka ,

We are closing this thread now due to long pending. Please reopen this thread if you have any other concerns or provided solution doesn't meet your requirements.
