### ISSUE TITLE
Diagram height and width wont be passed down to diagram_backgroundLayer_svg

### ISSUE THREAD

**Issue by Silom** [syncfusion/ej2-vue-ui-components#36]
Heyho.

I was updating "@syncfusion/ej2-vue-diagrams" from "17.3.29" to "17.4.44" and it appears to create some issues with heights passed down to diagram_backgroundLayer_svg.

Basically it renders with a fixed height on 'diagram_backgroundLayer_svg' with 400 something px even tho the parent as well as the diagram are almost double in size. That results in a diagram with a white cover under which nodes disappear when dragging them onto that.
I fixed it by reading the parent size and put :height="parentHeight" which works, but I think the old '100%' option was simpler.

The blue is the resulting 'ejs-diagram' dom element. The part where its cutting of is where 'diagram_backgroundLayer_svg' boundary ends.

<img width="189" alt="Screenshot 2020-02-04 at 12 17 13" src="https://user-images.githubusercontent.com/1633253/73740383-67a05680-4748-11ea-8c1f-d88ac24e79a4.png">
<img width="198" alt="Screenshot 2020-02-04 at 12 16 53" src="https://user-images.githubusercontent.com/1633253/73740384-67a05680-4748-11ea-8b69-de90bc8ecb14.png">

**Comment by gshyam93** [comment]
Hi Silom,

Could you please confirm us whether a diagram height is rendered partially at initial rendering or updating at runtime?. By default, when we set the diagram width and height in percentage, then the diagram size will be updated based on its parent size. So, please set diagram model height in pixel or set parent height in pixel. Still if you face problem, please share us more details such as code example of defining a diagram with the parent element in your application.

Regards,
Shyam G

**Comment by Sridhar-Narasimhan** [comment]
Marked this as closed considering no update for requested details and long time pending.
