### ISSUE TITLE
Slowness in DateRangepicker while Chrome Dev Tools Open

### ISSUE THREAD

**Issue by erhansaydam** [syncfusion/ej2-vue-ui-components#37]
Hello Syncfusion Team

As the title summarize, there is a slow run problem in Vue-Calendar component. When using Daterangepicker, it takes at least 1 second to open calendar as well as picking dates, exclusively when Chrome DevTools is open. The browser also tends to freeze. Might it be caused by a case when Devtools is open?

The case occurs in demo page as well. 
https://ej2.syncfusion.com/vue/demos/#/bootstrap4/daterangepicker/default.html

I would be happier if you analyze this problem. It does not occur if devtools is closed.

Best regards,
Erhan Saydam

**Comment by SevvandhiN** [comment]
Hi erhansaydam,  
 
Greetings from Syncfusion support.  
 
We have validated your reported requirement. We would like to inform that, the popup opening takes less than a minute which means that 180 milliseconds when Devtools is open.  Kindly refer the below screenshot,  

![image](https://user-images.githubusercontent.com/36529374/75628928-90125800-5c03-11ea-98fe-0b2df36159d3.png)


Also, in the Devtools closed state, it take 153 milli seconds to open the popup. But when you use the mobile mode , the popup rendering speed will be better performance comparing to the desktop mode. So we suggest to use the mobile for better performance. You can render the mobile mode popup in the created event by using below code snippet,  


`<ejs-daterangepicker ref=”dateRange” id="daterangepicker" :placeholder="waterMarkText"></ejs-daterangepicker>   

 this.$refs.dateRange.ejInstances.isMobile = “true” `


Regards,  
Sevvandhi N

**Comment by erhansaydam** [comment]
Hi Sevvandhi,

Thank you very much for your reply and detailed analyze. I have revealed that this problem occurs only in my Chrome browser whose version is 70. Beacuse of CORS problem I am keeping it on version 70. (Also my OS is Ubuntu 18)

I asked my friends (both Linux and Windows users) to test the component on their browsers, when devtool is open, they didn't get any slowness who have Chrome of 80's version. It can be thought that there might be a renewal for V8 engine.

Anyway, thank you for your interest and your help.

Best regards,
Erhan Saydam
