### ISSUE TITLE
Form Validation Link is broken in Vue Inplace Editor

### ISSUE THREAD

**Issue by bthanki** [syncfusion/ej2-vue-ui-components#47]
URL:  https://ej2.syncfusion.com/vue/documentation/inplace-editor/validation/

At the end of the page, the link for **section** in this particular text in broken. 

_For more details about validation configuration, refer this documentation section._

Right now it is pointing to https://ej2.syncfusion.com/vue/documentation/api/form-validator/

**Comment by Indrajith-Sync** [comment]
Hi @bthanki 

Greetings from Syncfusion support,

We have checked the reported link and it is broken. We will correct the documentation from our end and will be reflected in our live site with our **2020 Volume 2 Release**. 

Below is the correct link:

https://ej2.syncfusion.com/vue/documentation/form-validator/validation-rules/

Regards,
Indrajith

**Comment by Indrajith-Sync** [comment]
Hi @bthanki 

Thanks for your patience, 

We have corrected the broken link and the changes are refreshed in the live site.

https://ej2.syncfusion.com/vue/documentation/inplace-editor/validation/

Please let us know if you need any further assistance, 

Regards, 
Indrajith

**Comment by rajendranr-5483** [comment]
@bthanki ,

Thanks for notify us about breaking links.
