### ISSUE TITLE
QueryBuild can not addGroups

### ISSUE THREAD

**Issue by guozhqi** [syncfusion/ej2-vue-ui-components#49]
I copy the demo code from doc  (query-builder/getting-started) 
but  i can not see the addGroup btn in my page ,so  i try bind the method to my custom btns  click envent, the method throws 
exception also ,this is my demo 
![image](https://user-images.githubusercontent.com/14501481/86880579-78059480-c11f-11ea-8b5e-2a0d3660e115.png)
my local compent version is :18.1.56
thank for help

**Comment by saranya-dhayalan** [comment]
Hi Team,

Thank you for contacting Syncfusion support

We have checked your reported query, we are not able to reproduce it in our end. Please find the below code snippet:

`<template>
    <div class="control-section">
        <div class="col-lg-12 querybuilder-control">
            <ejs-querybuilder id="querybuilder" :dataSource="dataSource" :rule="importRules" width="70%">
                <e-columns>
                    <e-column field='EmployeeID' label='Employee ID' type='number' />
                    <e-column field='FirstName' label='First Name' type='string' />
                    <e-column field='TitleOfCourtesy' label='Title Of Courtesy' type='boolean' :values="values" />
                    <e-column field='Title' label='Title' type='string' />
                    <e-column field='HireDate' label='Hire Date' type='date' format='dd/MM/yyyy' />
                    <e-column field='Country' label='Country' type='string' />
                    <e-column field='City' label='City' type='string' />
                </e-columns>
            </ejs-querybuilder>
        </div>
    </div>
</template>
`

For your convenience, we have prepared a sample. Please find the below sample link

Sample link: https://codesandbox.io/s/vue-template-9e9jv?file=/src/App.vue

Please check the above sample and if still issue persists please reproduce your reported issue in the above sample and get back to us if you need further assistance on this.

Regards,
Saranya D

**Comment by guozhqi** [comment]
Thanks you  very much! I find the error from my css
