### ISSUE TITLE
Vue peer dependency version update

### ISSUE THREAD

**Issue by Blanen** [syncfusion/ej2-vue-ui-components#5]
Please update the peer dependency of 
https://github.com/syncfusion/ej2-vue-ui-components/blob/master/components/base/package.json#L27

to include 2.6.x.

It's not causing problems except for :
![image](https://user-images.githubusercontent.com/7236824/55812524-7055db00-5aeb-11e9-826d-73c38bf92275.png)
Which is annoying.

**Comment by Mydeen-SN** [comment]
Hi Banen,

Thanks for your suggestion.

We have updated our component peer dependencies and changes are reflected in the latest release.

https://github.com/syncfusion/ej2-vue-ui-components/releases/tag/v17.3.26

Regards,
Mydeen S N
