### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by wangmeng1991** [syncfusion/ej2-vue-ui-components#53]
![image](https://user-images.githubusercontent.com/33443928/96673566-6035e180-1399-11eb-9e22-419e76ff0d50.png)

**Comment by jesusarockias** [comment]
We have validated your requirement and we like to let you know that we have already logged a feature request on this and it can be tracked through our feedback portal below.

Link: https://www.syncfusion.com/feedback/16977/vue-3-support-for-ej2-vue-components

We expect that it will be included with our Volume 3, 2020 SP release. If you have any more specification/suggestions to the feature request you can add it as a comment in the portal.

We request your patience until then and please get back to us if you have any queries.

**Comment by wangmeng1991** [comment]
> We have validated your requirement and we like to let you know that we have already logged a feature request on this and it can be tracked through our feedback portal below.
> 
> Link: https://www.syncfusion.com/feedback/16977/vue-3-support-for-ej2-vue-components
> 
> We expect that it will be included with our Volume 3, 2020 SP release. If you have any more specification/suggestions to the feature request you can add it as a comment in the portal.
> 
> We request your patience until then and please get back to us if you have any queries.

OK 👌

**Comment by ensacta** [comment]
Is it supported yet?
