### ISSUE TITLE
Diagram gives "Cannot read property 'getSymbolSize' of undefined" error after npm update

### ISSUE THREAD

**Issue by erhansaydam** [syncfusion/ej2-vue-ui-components#54]
I have updated npm packages from these
"@syncfusion/ej2-vue-buttons": "^18.2.58",
"@syncfusion/ej2-vue-diagrams": "^18.2.59",
"@syncfusion/ej2-vue-lists": "^18.2.59",

to these
"@syncfusion/ej2-vue-buttons": "^18.3.40",
"@syncfusion/ej2-vue-diagrams": "^18.3.42",
"@syncfusion/ej2-vue-lists": "^18.3.35",

After this update, when I drag a symbol from palette to Diagram area, it throws the error:
Cannot read property 'getSymbolSize' of undefined
    at getPreviewSize (diagram-util.js?1ce4:2229)

My code is too big to paste here, I am bringing some of them here. But if needed I can paste the other parts.

Was there a change about the symbol size or else? 

Thank you,
Best regards.

```
...
<div id="networkDiagram" style="width: 100%; height: 600px">
  <div id="palette-space" class="sb-mobile-palette">
    <ejs-symbolpalette ref="paletteObj" id="symbolpalette" :palettes='palettes' :width='paletteWidth'
        :key="increment" :height='paletteHeight' :getNodeDefaults='palettegetNodeDefaults'
        :getSymbolInfo='getSymbolInfo' :symbolWidth='symbolWidth'
        :symbolHeight='symbolHeight'></ejs-symbolpalette>
  </div>
  <div id="diagram-space" class="sb-mobile-diagram">
    <ejs-diagram style='display:block' ref="diagramObj" id="diagram2" :width='width' :height='height'
        :nodes='nodes' :connectors='connectors' :getNodeDefaults='getNodeDefaults' :snapSettings='snapSettings'
       serializationSettings="{preventDefaults: true}"
        :doubleClick="openAddInfo"></ejs-diagram>
  </div>
</div>
...

palettegetNodeDefaults(symbol) {
      symbol.width = 52;
      symbol.height = 52;
      (symbol.shape).scale = "Stretch";
   },
getNodeDefaults: (node) => {
        node.constraints = NodeConstraints.Default & ~NodeConstraints.Rotate & ~NodeConstraints.Resize;
        return node;
      },
collectionChanged: (args) => {
        this.collectionChangeEvent(args);
      },

```

**Comment by KameshRajandran** [comment]
Hi @erhansaydam ,

Reported Issue : When Drag and drop the node from palette exception throws 
      
We can reproduce the issue and confirmed this as a defect. We have logged a defect report for this issue. We will fix this issue and provide the patch on October 27th 2020 weekly patch release.    
  
https://www.syncfusion.com/feedback/19126/when-drag-and-drop-the-node-from-palette-exception-throws    
    
Regards,    
Aravind Ravi
