### ISSUE TITLE
Changelog URL invalid

### ISSUE THREAD

**Issue by darthf1** [syncfusion/ej2-vue-ui-components#55]
The changelog url in `readme.md` refers to https://ej2.syncfusion.com/vue/documentation/release-notes?utm_source=npm&utm_campaign=ej2-vue-ui-components, but the page seems to be not working anymore.

Where can we find the current changelog?

**Comment by ajithr** [comment]
@darthf1 Sorry for the inconvenience. Please refer to the below link for the changelog.

https://ej2.syncfusion.com/vue/documentation/release-notes/index/

We have updated the same in the `README.md` file now.

https://github.com/syncfusion/ej2-vue-ui-components#changelog
