### ISSUE TITLE
ej2-vue-gantt on npm has not been updated

### ISSUE THREAD

**Issue by haodaking** [syncfusion/ej2-vue-ui-components#6]
Please update ej2-vue-gantt on npm to v17.1.44.
Thank you

**Comment by manikandanmanikam-syncfusion** [comment]
Hi Haodaking,
We  will publish the NPM packages only if we have done any major changes like including bug fixes or feature implementation. Until you can use the 17.1.43 which contain all latest changes.
Thanks,
Manikandan M.
