### ISSUE TITLE
Assign datasource after value in MultiSelect component

### ISSUE THREAD

**Issue by Rizzato95** [syncfusion/ej2-vue-ui-components#61]
Hi,
if I assign the `value` property and after that the `datasource` property in a MultiSelect component, values are not displayed.
The problem occurred from the 18 version, before (with 17.4.51) it worked correctly.

Here you can find an example with a simple `setTimeout` for reproduce the issue:
https://codesandbox.io/s/syncufsion-v18-multi-select-b5ond?file=/src/App.vue

Thanks.

**Comment by SevvandhiN** [comment]
Hi Rizzato,


Greetings from Syncfusion support.


We checked the shared sample. We provided custom value support to the MultiSelect component in the latest version. You can now use the allowCustomValue property to resolve the reported issue. The number values will appear in the input element till the data source is loaded into the component. If a data source is loaded, the corresponding text will be updated to the component. Please see the below code.


```
<ejs-multiselect
      id="multiSelect"
      :dataSource="dataSource"
      :fields="{
        text: 'name',
        value: 'id',
      }"
      :allowCustomValue="value"
      :value="values"
    ></ejs-multiselect>

  export default {
    data() {
      return {
        dataSource: [],
        textField: "ShipName",
        values: [1, 3],
        value: true,
      };
    },
```

Please find the sample below.



Sample link: https://codesandbox.io/s/syncufsion-v18-multi-select-forked-10dwb?file=/src/App.vue:440-584



Please check the above attached sample and get back to us if you need further assistance.



Regards,
Sevvandhi N

**Comment by Rizzato95** [comment]
Hi @SevvandhiN,

thanks for the quick reply.
The solution worked perfectly. 

Regards,
Marco Rizzato.
