### ISSUE TITLE
panel.content can not work module by Vue.component created

### ISSUE THREAD

**Issue by zouliuyun** [syncfusion/ej2-vue-ui-components#62]
ejs-dashboardlayout ： panel.content can not work module by Vue.component created
    "@syncfusion/ej2-base": "^18.4.44",
    "@syncfusion/ej2-charts": "^18.4.41",
    "@syncfusion/ej2-layouts": "^18.4.47",
    "@syncfusion/ej2-vue-base": "^18.4.42",
    "@syncfusion/ej2-vue-buttons": "^18.4.46",
    "@syncfusion/ej2-vue-charts": "^18.4.41",
    "@syncfusion/ej2-vue-dropdowns": "^18.4.47",
    "@syncfusion/ej2-vue-layouts": "^18.4.47",

error msg:
![image](https://user-images.githubusercontent.com/6251153/111567387-d409d800-87d9-11eb-9d33-c6d0207885bf.png)

![image](https://user-images.githubusercontent.com/6251153/111567062-4ded9180-87d9-11eb-8eed-f0a2f0056e76.png)

#61

**Comment by SharonSanchez** [comment]
Hi Team,

Greetings from Syncfusion Support.

We have checked your reported query with mentioned package version. But we are unable to predict the exact scenario in which the error occurs. 

To replicate this in our end, we have tried to update the panel content during mounted() event and it works fine. 

We have created a sample here for your reference. In the second panel, we are adding content dynamically for the panel.

Refer to the code snippet.
`mounted() {
    var dashboard = document.getElementById("edit_dashboard").ej2_instances[0];
    dashboard.panels[1].content = "<div>1</div>";
    this.$refs.accumulationInstance.height = "100%";
    this.$refs.accumulationInstance.width = "100%";
  },
`
Refer to the below sample.

https://codesandbox.io/s/vue-dashboard-template-forked-rv2co

Please check with the below links to know more about Dashboard Layout component.

Demo: https://ej2.syncfusion.com/vue/demos/#/material/dashboard-layout/default.html

Documentation: https://ej2.syncfusion.com/vue/documentation/dashboard-layout/template/

API: https://ej2.syncfusion.com/vue/documentation/api/dashboard-layout/

If the issue persists, please get back to us by modifying the above sample similar to your scenario for further assistance.

Regards,

Syncfusion Team.

**Comment by Thirukumanaran** [comment]
Hi @zouliuyun,

Please feel free to contact us if you experience any further problems/issues.

Regards,
Thirukumaran M.
