### ISSUE TITLE
ej2-vue-schedule Uncaught TypeError: Cannot read property 'quickPopupHide' of undefined

### ISSUE THREAD

**Issue by wangmeng1991** [syncfusion/ej2-vue-ui-components#63]
"@syncfusion/ej2-vue-calendars": "^18.4.51",
    "@syncfusion/ej2-vue-diagrams": "^18.4.55",
    "@syncfusion/ej2-vue-grids": "^18.4.55",
    "@syncfusion/ej2-vue-querybuilder": "^18.4.51",
    "@syncfusion/ej2-vue-schedule": "^18.4.55",

![image](https://user-images.githubusercontent.com/33443928/111969313-0e0a0f80-8b35-11eb-9915-2d2ecd0cb9be.png)

<img width="627" alt="Uncaught TypeError Cannot read propertyquickPopupHide' of undefined" src="https://user-images.githubusercontent.com/33443928/111969019-c4212980-8b34-11eb-9135-38211d10263e.png">

When I drag the node this is not working

**Comment by Balasubramanian-Sattanathan** [comment]
Dear customer,

We have checked your reported problem **“Cannot read property 'quickPopupHide' of undefined”** at our end and let you know that we have resolved this issue internally and it will be included in our Volume 1, 2021 main release and would appreciate your valuable patience until then.

Regards,
Balasubramanian S

**Comment by Nevitha-Ravi** [comment]
Dear Customer,

We are glad to announce that the reported issue has been resolved in our latest volume 1, 2021 main release v19.1.54. So please upgrade your version and check.

Regards,
Nevitha
