### ISSUE TITLE
[Question] How can I show context menu on command button click?

### ISSUE THREAD

**Issue by sunhillbd** [syncfusion/ej2-vue-ui-components#67]
## Context menu is working in grid on right mouse click, but I've to show the context menu on command button click too. 
See image

![image](https://user-images.githubusercontent.com/8676756/115515893-643eaf80-a2a7-11eb-9e1e-14270cf2ad9f.png)

#### Here is my command click method-

```
commandClick(args) {   
      let contextMenuObj = this.$refs.grid.ej2Instances.contextMenuModule.contextMenu;   
      contextMenuObj.open(40,20);
}
```
#### Getting folowing error
`Uncaught TypeError: Cannot read property 'target' of null`

**Comment by Gayathri02-design** [comment]
Hi Nahidul, 
 
Thank you for contacting Syncfusion support.

We have checked your reported query. We can show the contextMenu with command buttons in grid component. So, we have prepared sample in that we have added the click event to the Grid content and also used the commandClick event of the Grid component to show the contextMenu with command buttons. Please check the sample.

Sample Link: https://codesandbox.io/s/vue-template-forked-k54d0?file=/src/App.vue:4156-4783 

Please get back to us if you need further assistance. 

Regards, 
Gayathri K

**Comment by sunhillbd** [comment]
Hello @Gayathri02-design , 

Thank you for your quick support.
