### ISSUE TITLE
Is Vue 3 supported?

### ISSUE THREAD

**Issue by jhgeluk** [syncfusion/ej2-vue-ui-components#68]
Hi,

I'm trying to use the QueryBuilder component in Vue 3, however I can't get it to work.

Is there any update for this?

**Comment by jesusarockias** [comment]
Sorry for the inconvenience.

Currently, we do not have Vue 3 support for Syncfusion Vue components and we expect that it will be included with our Volume 2, 2021 release scheduled in the end of this month. You can track the progress using the following feedback link.

https://www.syncfusion.com/feedback/16977/vue-3-support-for-ej2-vue-components

**Comment by jesusarockias** [comment]
We are glad to announce that our Essential Studio 2021 Volume 2 release v19.2.0.44  is rolled out and is available for download under the following link.

https://www.syncfusion.com/forums/166800/essential-studio-2021-volume-2-main-release-v19-2-0-44-is-available-for-download

We have included the support “Vue 3 for Syncfusion EJ2 Components”.

https://www.syncfusion.com/feedback/16977/vue-3-support-for-ej2-vue-components

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.
