### ISSUE TITLE
@syncfusion/ej2-vue-inputs is not working in Vue 3

### ISSUE THREAD

**Issue by azizullahsaeidi** [syncfusion/ej2-vue-ui-components#78]
ej2-vue-inputs is working nice with vue2 but after upgrading to vue 3, now it doesn't work. 
The current version of ej2-vue-input in my project is 19.3.53

`"@syncfusion/ej2-vue-inputs": "^19.3.53",`

Error
`./node_modules/@syncfusion/ej2-vue-inputs/src/uploader/files.directive.js 29:16-19
export 'default' (imported as 'Vue') was not found in 'vue' `

**Comment by dmytro-seredenko** [comment]
@azizullahsaeidi, I have the same issue. Do you use `Vite` or `Rollup`? With these tools, the project is failing to build for me either. `Webpack` still works but throws these things like warnings and not as errors.

**Comment by dmytro-seredenko** [comment]
As a possible workaround.

In vite config configure an alias

```
vue: `${path.resolve(__dirname, 'src')}/vue-shim.ts`,
'vue-custom': `vue/dist/vue.esm-bundler.js`,
```


Inside `vue-shim.ts` 

```
// @ts-ignore
export * from 'vue-custom';
export default null;
```

**Comment by David-C-gd-y** [comment]
You can change the compile setting. 
The reason is that the source code uses Vue3 incorrectly. 
Vue 3 does not have a default export
This is the case I used in vite.

The vue used in the project is no longer node_modules, but a custom ImportVue.ts.

Vite config:
---
``` javascript
resolve: {
      alias: [
         {
          find: 'vue',
          replacement: path.resolve(__dirname, './ImportVue.ts'), 
        },
      ],
    },
```
create ImportVue.ts file.
-
```javascript
import * as V from './node_modules/vue/dist/vue.esm-bundler.js';

export * from './node_modules/vue/dist/vue.esm-bundler.js';

export default V;
```
After completing these two steps, the project will run.

**Comment by BerlyChristopher94** [comment]
Hi David,

Thanks for sharing the solution with us. Please let us know if you need further assistance on this.

Regards,
Berly B.C
