### ISSUE TITLE
Cannot see the black arrow to drop down subtasks next to ID 

### ISSUE THREAD

**Issue by zygisjas** [syncfusion/ej2-vue-ui-components#8]
I'm not sure if it's a specific option or it should work by default, but I cannot see those little black triangles to make a drop down of subtasks. Maybe someone had a similar issue?

**Comment by ChristoIssac** [comment]
Hi zygisjas,

We are unclear with your actual issue. Please get back to us with more details like,

1. Which control (dropdownList or DropdownButton or any other) you are facing such issues?
2. In which scenario you are getting this issue or Is it possible to provide us some steps to replicate the issue?

**Comment by zygisjas** [comment]
The issue was with the black drop down triangle that is by default on ID at the left side, when you have subtasks, you can hide subtasks, and vice versa.
The issue was CSS, although, all proviced css's were imported, I had to add some additional css to make it working.
