### ISSUE TITLE
Vue3 support for ejs-treegrid component

### ISSUE THREAD

**Issue by kquadri** [syncfusion/ej2-vue-ui-components#80]
Team, any plan to support Vue3 in [ejs-treegrid component](https://ej2.syncfusion.com/vue/documentation/treegrid/getting-started/)?

**Comment by ManivannanPadmanaban** [comment]
Hi Mohammad Kashif Quadri,

Greetings from Syncfusion Support.

We are glad to inform you that our controls will support in Vue 3 which includes Tree Grid too. For your convenience, we have prepared the Tree Grid sample in Vue 3. Please refer to the below link for sample. 
https://www.syncfusion.com/downloads/support/directtrac/general/ze/vue3-treegrid80592098618009641.zip

We will add the Vue 3 support details in our Tree Grid help documentation and the same will be refreshed online by the mid of March 2022. Kindly get back to us, if you need any further assistance. We will be happy to assist you. 

Regards, 
Manivannan Padmanaban
