### ISSUE TITLE
Can not make grid editing work with vue 3

### ISSUE THREAD

**Issue by alaarihan-temco** [syncfusion/ej2-vue-ui-components#81]
Hi,

I tried everything before I open this issue, I think there is a problem with  `provide` `Edit` or with provide in general, I think `provide` works in different way in vue 3..
You can check this example that should work perfectly because I copied it from your documentation examples with vue 3 necessary modifications:
https://codesandbox.io/s/lingering-silence-0z2h9?file=/src/App.vue

As you will see, the grid is working but without editing functionality.

**Comment by BalajiSGrid** [comment]
We checked the reported problem with provided the information and we found that you have used the **provide** inside of **data** section in the Vue sample it is cause of the problem

In the below sample, we have moved the **provide** from the **data** section to a separate section of Vue 3 sample then Grid will perform the Edit action properly.

Please refer to the below sample for more information.

**Sample link**: https://codesandbox.io/s/quirky-bose-e1961k?file=/src/App.vue

**Comment by syncsiva** [comment]
This issue has been resolved and has not had any activity for 2 days. Closing for housekeeping purposes. Please feel free to reopen if you have any further queries.
