### ISSUE TITLE
The spreadsheet component cannot be successfully rendered with Vue 3

### ISSUE THREAD

**Issue by YukiEF4FDH** [syncfusion/ej2-vue-ui-components#82]
Hi, I followed your [Getting Started instructions with Vue 3](http://getting%20started%20with%20vue%203%20in%20vue%20spreadsheet%20component/) updated on 09 Mar 2022,
with things below:

- Vue CLI v4.5.11
- vue-class-component : 8.0.0-rc.1
- ej2-vue-spreadsheet@19.4.55

and I think that there might be some problems with the Vue 3 version.

The rendered page is like this:
![](https://gyazo.com/4e436b48c09ed369377872cb9a42c64a.png)
with the grids below:
![](https://gyazo.com/e4cad95eb8f05af22f3bea2c452abc43.png)

And here's the warning:
```
 warning  in ./node_modules/@syncfusion/ej2-vue-base/src/template.js
"export 'extend' (imported as 'Vue') was not found in 'vue'
```
I think this might be occurred by the problem that Vue.extend is not supported any more in Vue 3...

By the way, this rendering problem seems cannot be solved by simply replacing Vue.extend with Vue.defineComponent, Vue.createApp, or something else. By doing these, the warning won't show up but the rendering remained the same.

This spreadsheet component works well with Vue 2 on my PC.

**Comment by sangeetha-priya-M** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/SANGEE~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/SANGEE~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/SANGEE~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link="#0563C1" vlink="#954F72" style='tab-interval:.5in;
word-wrap:break-word'>


<p class=MsoNormal style='margin-bottom:0in;line-height:115%'><span
style='mso-bidi-font-family:Calibri;mso-bidi-theme-font:minor-latin'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:115%'><span
style='mso-bidi-font-family:Calibri;mso-bidi-theme-font:minor-latin'>Hi Yuki,<o:p></o:p></span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:115%'><span
style='mso-bidi-font-family:Calibri;mso-bidi-theme-font:minor-latin'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:115%'><span
style='mso-bidi-font-family:Calibri;mso-bidi-theme-font:minor-latin'>We have
created the sample based on the documentation and the CSS issue occurs in our
end. So, we have prepared the sample with below dependent CSS references and the
spreadsheet render properly in our end. Please find the link below.<o:p></o:p></span></p>

<p class=MsoNormal style='margin-bottom:0in'><o:p>&nbsp;</o:p></p>



<style>     @import   '../node_modules/@syncfusion/ej2-base/styles/material.css';       @import   '../node_modules/@syncfusion/ej2-buttons/styles/material.css';       @import '../node_modules/@syncfusion/ej2-dropdowns/styles/material.css';       @import   '../node_modules/@syncfusion/ej2-inputs/styles/material.css';       @import   '../node_modules/@syncfusion/ej2-navigations/styles/material.css';     @import   '../node_modules/@syncfusion/ej2-popups/styles/material.css';     @import   '../node_modules/@syncfusion/ej2-splitbuttons/styles/material.css';     @import   '../node_modules/@syncfusion/ej2-grids/styles/material.css';     @import ../node_modules/@syncfusion/ej2-vue-spreadsheet/styles/material.css;   </style>
--




<p class=MsoNormal style='margin-bottom:0in;line-height:115%'><span
style='mso-bidi-font-family:Calibri;mso-bidi-theme-font:minor-latin'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:115%'><span
style='mso-bidi-font-family:Calibri;mso-bidi-theme-font:minor-latin'>Sample
Link: <a
href="https://www.syncfusion.com/downloads/support/directtrac/general/ze/vue3-grid-getting-started-main-1728041865">https://www.syncfusion.com/downloads/support/directtrac/general/ze/vue3-grid-getting-started-main-1728041865</a>
<o:p></o:p></span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:115%'><span
style='mso-bidi-font-family:Calibri;mso-bidi-theme-font:minor-latin'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:12.65pt'><span
style='mso-bidi-font-family:Calibri;mso-bidi-theme-font:minor-latin;color:black;
background:white'>However, we will consider this and correct our online help documentation
site and we will let you know once it is refreshed in live. We appreciate your
patience until then.<o:p></o:p></span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:12.65pt'><span
style='mso-bidi-font-family:Calibri;mso-bidi-theme-font:minor-latin;color:black;
background:white'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:12.65pt'><span
style='mso-bidi-font-family:Calibri;mso-bidi-theme-font:minor-latin;color:black;
background:white'>Regards,<o:p></o:p></span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:12.65pt'><span
style='mso-bidi-font-family:Calibri;mso-bidi-theme-font:minor-latin;color:black;
background:white'>Sangeetha M<o:p></o:p></span></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>


</body>

</html>
Hi Yuki,

We have created the sample based on the documentation and the CSS issue occurs in our end. So, we have prepared the sample with below dependent CSS references and the spreadsheet render properly in our end. Please find the link below.


<style>
  @import '../node_modules/@syncfusion/ej2-base/styles/material.css';  
  @import '../node_modules/@syncfusion/ej2-buttons/styles/material.css';  
  @import '../node_modules/@syncfusion/ej2-dropdowns/styles/material.css';  
  @import '../node_modules/@syncfusion/ej2-inputs/styles/material.css';  
  @import '../node_modules/@syncfusion/ej2-navigations/styles/material.css';
  @import '../node_modules/@syncfusion/ej2-popups/styles/material.css';
  @import '../node_modules/@syncfusion/ej2-splitbuttons/styles/material.css';
  @import '../node_modules/@syncfusion/ej2-grids/styles/material.css';
  @import [../node_modules/@syncfusion/ej2-vue-spreadsheet/styles/material.css](mailto:../node_modules/@syncfusion/ej2-vue-spreadsheet/styles/material.css);
</style>

Sample Link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/vue3-grid-getting-started-main-1728041865 

However, we will consider this and correct our online help documentation site and we will let you know once it is refreshed in live. We appreciate your patience until then.

Regards,
Sangeetha M

**Comment by sangeetha-priya-M** [comment]
Hi Yuki,

We have created the sample based on the documentation and the CSS issue occurs in our end. So, we have prepared the sample with dependent CSS references and the spreadsheet render properly in our end. Please find the link below.

Sample Link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/vue3-grid-getting-started-main-1728041865 

However, we will consider this and correct our online help documentation site and we will let you know once it is refreshed in live. We appreciate your patience until then.

Regards,
Sangeetha M

**Comment by sangeetha-priya-M** [comment]
HI Yuki,

We have updated our documentation and refreshed in live. Please find the link below.

https://ej2.syncfusion.com/vue/documentation/spreadsheet/getting-started-vue/#adding-css-reference 

Could you please check the above link and get back to us, if you need any further assistance on this.

Regards,
Sangeetha M
