### ISSUE TITLE
multiselect 'checkbox' Mode Error: Cannot read properties of null (reading 'setAttribute')"

### ISSUE THREAD

**Issue by fancyhejianyang** [syncfusion/ej2-vue-ui-components#89]
```
<template>
  <div class="col-lg-12 control-section">
    <div class="content-wrapper">
      <div>
        <ejs-multiselect
          id="workWeekDays"
          cssClass="schedule-workweek"
          width="500px"
          :dataSource="weekDays"
          enableSelectionOrder="false"
          showClearButton="false"
          showDropDownIcon="true"
          :fields="fields"
          :mode="checkboxMode"
          popupHeight="150px"
          @change="onWorkWeekDayChange"
          :value="value"
        >
        </ejs-multiselect>
      </div>
    </div>
  </div>
</template>

<script>
import Vue from "vue";
import { GridPlugin, Selection } from "@syncfusion/ej2-vue-grids";
import { MultiSelectPlugin } from "@syncfusion/ej2-vue-dropdowns";

Vue.use(GridPlugin);
Vue.use(MultiSelectPlugin);
export default {
  name: "Demo",
  data() {
    return {
      weekDays: [
        {
          text: "周日",
          value: 0,
        },
        {
          text: "周一",
          value: 1,
        },
        {
          text: "周二",
          value: 2,
        },
        {
          text: "周三",
          value: 3,
        },
        {
          text: "周四",
          value: 4,
        },
        {
          text: "周五",
          value: 5,
        },
        {
          text: "周六",
          value: 6,
        },
      ],
      checkboxMode: 'CheckBox',
      fields: { text: "text", value: "value" },
      value: [1, 2],
    };
  },
  methods: {
    onWorkWeekDayChange(params) {
      console.log(params)
      this.workDays = params.value
    }
  },
  provide: {
    grid: [Selection],
  },
};
</script>
```
When select any item or fresh page, error occur like this:
![image](https://user-images.githubusercontent.com/17957478/192778329-e92ad9fa-cc6e-40fa-871b-27105a817e57.png)

the ej2 version is:
![image](https://user-images.githubusercontent.com/17957478/192778507-aa7f2303-fa78-41a2-bb35-88b12201eb13.png)

**Comment by Sureshkumar2288** [comment]
when you use checkbox mode, inject the CheckBoxSelection module in the MultiSelect.

Find the code example here:
`<template>

  <div id="app">

    <div id='container' style="margin:50px auto 0; width:250px;">

      <ejs-multiselect

          id="workWeekDays"

          cssClass="schedule-workweek"

          width="500px"

          :dataSource="weekDays"

          enableSelectionOrder="false"

          showClearButton="false"

          showDropDownIcon="true"

          :fields="fields"

          :mode="checkboxMode"

          popupHeight="150px"

          :change="onWorkWeekDayChange"

          :value="value"

        >

        </ejs-multiselect>
    </div>
  </div>
</template>`
`<script>

import Vue from 'vue';

import { MultiSelectPlugin  } from "@syncfusion/ej2-vue-dropdowns";

import { MultiSelect, CheckBoxSelection } from '@syncfusion/ej2-dropdowns';

MultiSelect.Inject(CheckBoxSelection);
Vue.use(MultiSelectPlugin);

export default {

  data() {

    return {

     weekDays: [

        {

          text: "周日",

          value: 0,

        },

        {

          text: "周一",

          value: 1,

        },

        {

          text: "周二",

          value: 2,

        },

        {

          text: "周三",

          value: 3,

        },

        {

          text: "周四",

          value: 4,

        },

        {

          text: "周五",

          value: 5,

        },

        {

          text: "周六",

          value: 6,

        },

      ],

      checkboxMode: 'CheckBox',

      fields: { text: "text", value: "value" },

      value: [1, 2],

    }

  },

  methods: {

 

    onWorkWeekDayChange(params) {

      console.log(params)

      this.workDays = params.value

    }

 

  }

}
</script>`

To know more about the checkbox mode rendering, please refer to the documentation here: https://ej2.syncfusion.com/vue/documentation/multi-select/checkbox/

Regards,

Sureshkumar P

**Comment by syncsiva** [comment]
This issue has not had any activity for a week. Closing for housekeeping purposes. Please feel free to reopen it if you have more information that can help us investigate the issue further.
