### ISSUE TITLE
Tried... crashed and failed.. back to Tailwind ))

### ISSUE THREAD

**Issue by tvld** [syncfusion/ej2-vue-ui-components#93]
Last night I stumbled on your beautiful components. Greenfield project with Vue 3 / Vite, So thought to give it a try. Tow hours later, it seems the best is to give up:

1. SF seems to need '  ``vue-class-component`` as per the [documentation](https://ej2.syncfusion.com/vue/documentation/getting-started/vue3-tutorial/). That does not make me feel ok, as Vue 3 seems to not like that anymore. I tried anyway: but nowhere you write how to install it for Vue 3. ``npm install vue-class-component`` does not work. I ended up adding ``  "vue-class-component": "8.0.0-rc.1",`` to package.json and ran ``npm install``
2. I tried to make a button and it is there, along with the license warning. We are 1 person startup so, I assume that we could get over with. I did not figure out how though.
3. Unfortunately I get in vs-code:
```
let ButtonComponent: typeof ButtonComponent
Type '{ cssClass: string; }' is not assignable to type 'ComponentProps<typeof ButtonComponent>'.
  Property 'prototype' is missing in type '{ cssClass: string; }' but required in type 'typeof ButtonComponent'.ts(2322)
```
4. There is no ``syncfusion`` package in vs-codium, only the [closed source variant](https://marketplace.visualstudio.com/items?itemName=SyncfusionInc.Web-VSCode-Extensions).  So we can not install the package obviously. Maybe it would get rid of the error mentioned above. Dont know...

All in all: there is *a lot* going on in Syncfusion, but is seems maybe too much to be a jack-of-all trade and less focussed on giving a specific developer in this case in Vue 3, a smooth ride... ? ))

**Comment by RagunathSF3421** [comment]
Hi @tvld,

Greetings from Syncfusion support.

**Query 1: SF seems to need ' vue-class-component as per the documentation. That does not make me feel ok, as Vue 3 seems to not like that anymore. I tried anyway: but nowhere you write how to install it for Vue 3. npm install vue-class-component does not work. I ended up adding "vue-class-component": "8.0.0-rc.1", to package.json and ran npm instal**l
Our Syncfusion vue 3 component needs Vue-class-component as a dependency. So, please run the below command to install the vue-class-component in your application.
`npm install vue-class-component@8.0.0-rc.1`

**Query 2: I tried to make a button and it is there, along with the license warning. We are 1 person startup so, I assume that we could get over with. I did not figure out how though.**
We have introduced license key validation for Essential JS2 platforms from the 2022 Volume 1 release(v20.1.47). This licensing key validation will enforce the developer to register the valid licensing key in an application while referring to any of the latest packages, either from npm or CDN or build.

We also have a way to register the license key using the npx command. If you are facing issues while registering license key in the main.ts file, we suggest you to register the license key using npx command. We have provide the support, registering the license key using npx command in the volume 2 2022 release (v20.2.0.36),

For generating and registering a license key please refer to the following documentation.
https://ej2.syncfusion.com/vue/documentation/licensing/license-key-generation/
https://ej2.syncfusion.com/vue/documentation/licensing/license-key-registration/
https://www.syncfusion.com/blogs/post/introducing-license-key-validation-for-the-essential-js-2-platforms.aspx

**Query 3: Unfortunately I get in vs-code:**
We have created a Vue 3/Vite application, and it is working fine at our end. Please refer to the below sample. Also, we have attached the documentation of the steps to create the application.
Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/Vue3-button-390601807
Documentation: https://www.syncfusion.com/downloads/support/directtrac/general/doc/Vite-document-215152296

Please get back to us if you have any queries.

Regards,
Ragunath S

**Comment by syncsiva** [comment]
This issue has not had any activity for 2 weeks. Closing for housekeeping purposes. Please feel free to reopen it if you have more information that can help us investigate the issue further.
