### ISSUE TITLE
The requested module '@syncfusion/ej2-vue-circulargauge' is a CommonJS module, which may not support all module.exports as named export

### ISSUE THREAD

**Issue by polymer-coder** [syncfusion/ej2-vue-ui-components#99]
After building, this error presents itself

`
Named export 'Annotations' not found. The requested module '@syncfusion/ej2-vue-circulargauge' is a CommonJS module, which may not support all module.exports as named exports. CommonJS modules can always be imported via the default export, for example using: import pkg from '@syncfusion/ej2-vue-circulargauge'; const { CircularGaugeComponent, AxesDirective, AxisDirective, PointersDirective, PointerDirective, RangesDirective, RangeDirective, Gradient, Annotations } = pkg;
`

Framework: Nuxt 3.4.3
Dependency Versions: 
    @syncfusion/ej2-base  21.2.3
    @syncfusion/ej2-vue-circulargauge -  21.2.3

`plugins/syncfusion.client.js`
```
import { registerLicense } from "@syncfusion/ej2-base";
import {
  CircularGaugePlugin,
  Annotations,
  Gradient,
  CircularGaugeComponent as EjsCirculargauge,
  AxesDirective as EAxes,
  AxisDirective as EAxis,
  PointersDirective as EPointers,
  PointerDirective as EPointer,
  RangesDirective as ERanges,
  RangeDirective as ERange,
} from "@syncfusion/ej2-vue-circulargauge";


const key = ""

// Registering Syncfusion license key
export default defineNuxtPlugin((nuxtApp) => {
  registerLicense(key);
  nuxtApp.vueApp.use(Annotations, Gradient, EjsCirculargauge, EAxes,EAxis, EPointers,EPointer, ERanges, ERange)
});
```

**Comment by indumathi-murali** [comment]
Dear Customer,



We are unable to reproduce the reported issue in the Vue application with Nuxt framework (3.4.3) and ej2-vue-circulargauge(21.2.3) package. Please find the sample, in which we tried to reproduce the issue, from the below link.



https://stackblitz.com/edit/github-zpyx8t-fek7aj?file=app.vue


![image](https://github.com/syncfusion/ej2-vue-ui-components/assets/57896631/2a760d8e-999f-4287-ae32-17e866fec997)


To enable the annotation feature, we need to inject “Annotations” module using “CircularGauge.Inject(Annotations)” method. Please ensure whether this code in included in your application. You can refer the above sample to resolve the reported issue.


If you are still facing the reported issue, please share us a video or the modify the above sample to reproduce the reported issue. It will be helpful for us to analyze and assist you further.

**Comment by polymer-coder** [comment]
Thanks @indumathi-murali can you try building the application for production alongside providing an example using the Compositions API?

**Comment by indumathi-murali** [comment]
Dear Customer,



We are unable to reproduce the reported issue using the Circular Gauge component with the composition API. Please see the link below for the sample in which we tried to reproduce the issue.

https://stackblitz.com/edit/vue-3-composition-api-demo-hxhegr


If you are still experiencing the reported problem, please modify the above sample to reproduce the issue or provide us with your sample in which the issue is reproduced. It will be helpful for us to analyze and assist you further.

**Comment by polymer-coder** [comment]
Hi @indumathi-murali I've recreated the issue here: https://stackblitz.com/edit/nuxt-starter-ko7lat

Please note the application will work in development `npm run dev` but when building for production `npm run build` and then `npm run serve` that's when the error occurs:
```
[nuxt] [request error] [unhandled] [500] Named export 'AnnotationDirective' not found. The requested module '@syncfusion/ej2-vue-circulargauge' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@syncfusion/ej2-vue-circulargauge';
const { Annotations, CircularGaugeComponent, AxesDirective, AxisDirective, PointersDirective, PointerDirective, AnnotationsDirective, AnnotationDirective, RangesDirective, RangeDirective } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)    
[nuxt] [request error] [unhandled] [500] Named export 'AnnotationDirective' not found. The requested module '@syncfusion/ej2-vue-circulargauge' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@syncfusion/ej2-vue-circulargauge';
const { Annotations, CircularGaugeComponent, AxesDirective, AxisDirective, PointersDirective, PointerDirective, AnnotationsDirective, AnnotationDirective, RangesDirective, RangeDirective } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)    
[nuxt] [request error] [unhandled] [500] Named export 'AnnotationDirective' not found. The requested module '@syncfusion/ej2-vue-circulargauge' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@syncfusion/ej2-vue-circulargauge';
const { Annotations, CircularGaugeComponent, AxesDirective, AxisDirective, PointersDirective, PointerDirective, AnnotationsDirective, AnnotationDirective, RangesDirective, RangeDirective } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)    
[nuxt] [request error] [unhandled] [500] Named export 'AnnotationDirective' not found. The requested module '@syncfusion/ej2-vue-circulargauge' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@syncfusion/ej2-vue-circulargauge';
const { Annotations, CircularGaugeComponent, AxesDirective, AxisDirective, PointersDirective, PointerDirective, AnnotationsDirective, AnnotationDirective, RangesDirective, RangeDirective } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
```

**Comment by polymer-coder** [comment]
Hi @indumathi-murali any feedback on this?

**Comment by polymer-coder** [comment]
@sabari-senthamaraikannan thank you for the update

**Comment by polymer-coder** [comment]
Hi @indumathi-murali the issue has been fixed! Thank you so much for the support.
